travis:
  secure:
    BINSTAR_TOKEN: ZZpDm1c453VI5O5qUPd6s97dt55Ssuyk9LN2bk8Tuy8tXH+hfVcGlgpVGsyWDQFUQfeV2Oj+0pMf68Tf84TEOtWjNf4AsN4rkJ8RdjdBY1dTbPNJ0+On4u0MMpbl6HsGU46AtrdP6/5Ys+jNbFCMk8TrIgzuqlJksPMUG2qQKxMxE6wLq8ObkrVi7oEQLcbB0y1jYJyEOopXgb7EPxD+mbrmRobJJyLXTLvdd1v4gAlEYvmaTX2Y+ZCMDBt+O8p/h8UXJ+7J6vapTZTY0Gi6jJJ92rtbTN00mfSsy9RtRzsPdunG1CDL6wILIqka2jqOSR3ajDZYgda5XcIsFK1F/qEPeu6i8Lr6XjbZUwm4aS5yhpK7AlGJhCGVn8bCNdBr30s1HlIlsYDREXdXFbGr69+SII8wX8fDtzoUsooIwOs754QfcVT8ZqrkuMityL8L69JPRMcZYJ7FqOE9DsTdp6MQECTXz3WqIOuJv04GZs1whYkCGmDVLoKfmZAjzZKSWIzLESo4/hp1q83IGpL2BQKz3S1gLM6pSHIqCPBokrPV2gavTiL2b7vHoNrPNevys4GW1YZ6SirYajd/vzkEal2dbhVRm/3vnlR8fQ2KifK1OA6PBdwLT0/6H4tOqdo8GllEI7i5kJi6HfiSG1tRoeQI1oPgfunlSsZxubPngnY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
