travis:
  secure:
    BINSTAR_TOKEN: bnNQQN/KbEXoroqOcqE0Mws9gNTNZXGMJ+9OTS+gN3TGTOMxqi3fskFKv3Ayg92/qMhgDsD2oH7SzdJ0LsqHGD6i2HHixA0AwOvR5ApBDh1u00mIC2RxA49cT48bxZhr4yRzs66KXDRXf53JSvyZWfpnf5N7287h5gb1tvMturTB2Dc8JLWjp/RPqQFDrGmVHs8dWuvD8fGet0sWJrl6KE6QVkZWKejlKv4MVikCzg/V3qG6+bMqW8bwM0aAJSaSKuVLKm/1r58DYy8yvN1gNxuMOVuxvTR9ICED3NJBp/pyng2N92O2fPblcOqxIwmOOJz+ZGh+3tc5uea88KqV8F4YwccW0jsGM/DbwgTKb65K6Gh3QJjs2ttEzQfCJk6uC7i2gr0vnWZWgZ7V2dlATPtvH/AUaWSkAIsdJTXDgABoKw16si5MxYtsVNX6Q/C+JL9oH2hBc+y8Mf135HGds0ghJZ7jYhgUExIgktxcucEy//vW6w2Zw1PHQquDvFkZYnMqIWRMcoaXe2MiLJXQpAeNcSfzWhszwGHmC0iBmS411RmchEgT10yoN08Cmo31aocPr83zQxFmGw81vI0zx0pf2aryJpIvYFE4oKsfgD7MJq87LF/2k5YCu7g2yFCI6KuS8SmKYBVkAnokA0UKuh3MG/DqfbpHjaAXlTg3Uk4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
