travis:
  secure:
    BINSTAR_TOKEN: ScM+0eeEohm0gIeJVNqh1qSpwx+t8v5X9YWNr4Shs8oH6cyDrVm9+ZQfqPQ19+ppaMMK/jLFe7hxoSZQgxPwXwLhQ7llloHLLmGqx1qItrdDqcRtDSlo/FNi1iVbAxnP+3RtoApgW6jAJYBun8ObzlKne1C1JRfzDonToexN+AnEOzC2K6sPdfxEv3KRPFQHrsffut6fbxwP9pHJnC6/JCfSYA879F0XaWOO9vf7/iw3C45YSE+dFlWT30aAJU2e+ByNUGDER41jwcLULXwsb+fATf6njr1jhCeVIX6jcLX8snmkT6KMtcJVF3FjY5SzX6qLafZNFopUeR8P1snt3f3g1IbjXb/dSw5bSFNh2770HFUw8cdiyWagXSlXFHs/lrOhTmt4obUrLrKsSf+DSny0KZ1Zq6P8+plXpGAuSy7/eBel5ZPu3PR7jZlw9MS6Y8mGOIKQDRjcEhK/7/YdY8ySOWApP2QEYVJla+7JAMZCClN9S7ZIERIBUvb2D6hivD8vsnI0spiY85GZ2mHxD8KBosZerVRZ+PlDVBgU18O6Bl5FEK2jVOB76KZkJ5iMlzcB+A+X/8ci/MLd74MP27oBybm1Ckr+QyBqPuVsODS53TTrxraQYg50uz9v4pOYPZby8a4ylYJl96OqJabTruPKkAA5hdT2dra2DAQnsvU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
